package com.teamj.distribuidas.model.database;
// Generated Feb 15, 2016 11:39:15 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Historico generated by hbm2java
 */
public class Historico  implements java.io.Serializable {


     private Integer codigo;
     private Date timestamp;
     private String usuarioCodigo;
     private String descripcion;

    public Historico() {
    }

    public Historico(String usuarioCodigo, String descripcion) {
       this.usuarioCodigo = usuarioCodigo;
       this.descripcion = descripcion;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public String getUsuarioCodigo() {
        return this.usuarioCodigo;
    }
    
    public void setUsuarioCodigo(String usuarioCodigo) {
        this.usuarioCodigo = usuarioCodigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


