package com.teamj.distribuidas.model.database;
// Generated Feb 15, 2016 11:39:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Opcion generated by hbm2java
 */
public class Opcion implements java.io.Serializable {

    private Integer codigo;
    private Sistema sistema;
    private Opcion opcion;
    private String nombreOpcion;
    private String descripcion;
    private String nivel;
    private Set opcions = new HashSet(0);
    private Set ventanas = new HashSet(0);
    private Set opcionDePerfils = new HashSet(0);

    public Opcion() {
    }

    public Opcion(Sistema sistema, String nombreOpcion) {
        this.sistema = sistema;
        this.nombreOpcion = nombreOpcion;
    }

    public Opcion(Sistema sistema, Opcion opcion, String nombreOpcion, String descripcion, String nivel, Set opcions, Set ventanas, Set opcionDePerfils) {
        this.sistema = sistema;
        this.opcion = opcion;
        this.nombreOpcion = nombreOpcion;
        this.descripcion = descripcion;
        this.nivel = nivel;
        this.opcions = opcions;
        this.ventanas = ventanas;
        this.opcionDePerfils = opcionDePerfils;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Sistema getSistema() {
        return this.sistema;
    }

    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }

    public Opcion getOpcion() {
        return this.opcion;
    }

    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }

    public String getNombreOpcion() {
        return this.nombreOpcion;
    }

    public void setNombreOpcion(String nombreOpcion) {
        this.nombreOpcion = nombreOpcion;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getNivel() {
        return this.nivel;
    }

    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    public Set getOpcions() {
        return this.opcions;
    }

    public void setOpcions(Set opcions) {
        this.opcions = opcions;
    }

    public Set getVentanas() {
        return this.ventanas;
    }

    public void setVentanas(Set ventanas) {
        this.ventanas = ventanas;
    }

    public Set getOpcionDePerfils() {
        return this.opcionDePerfils;
    }

    public void setOpcionDePerfils(Set opcionDePerfils) {
        this.opcionDePerfils = opcionDePerfils;
    }

    @Override
    public String toString() {
        return nombreOpcion;
    }

}
