package com.teamj.distribuidas.model.database;
// Generated Feb 15, 2016 11:39:15 PM by Hibernate Tools 3.6.0



/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer codigo;
     private OpcionDePerfil opcionDePerfil;
     private String insertar;
     private String consultar;
     private String modificar;
     private String eliminar;

    public Rol() {
    }

	
    public Rol(OpcionDePerfil opcionDePerfil) {
        this.opcionDePerfil = opcionDePerfil;
    }
    public Rol(OpcionDePerfil opcionDePerfil, String insertar, String consultar, String modificar, String eliminar) {
       this.opcionDePerfil = opcionDePerfil;
       this.insertar = insertar;
       this.consultar = consultar;
       this.modificar = modificar;
       this.eliminar = eliminar;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public OpcionDePerfil getOpcionDePerfil() {
        return this.opcionDePerfil;
    }
    
    public void setOpcionDePerfil(OpcionDePerfil opcionDePerfil) {
        this.opcionDePerfil = opcionDePerfil;
    }
    public String getInsertar() {
        return this.insertar;
    }
    
    public void setInsertar(String insertar) {
        this.insertar = insertar;
    }
    public String getConsultar() {
        return this.consultar;
    }
    
    public void setConsultar(String consultar) {
        this.consultar = consultar;
    }
    public String getModificar() {
        return this.modificar;
    }
    
    public void setModificar(String modificar) {
        this.modificar = modificar;
    }
    public String getEliminar() {
        return this.eliminar;
    }
    
    public void setEliminar(String eliminar) {
        this.eliminar = eliminar;
    }




}


