package com.teamj.distribuidas.model.database;
// Generated Feb 15, 2016 11:39:15 PM by Hibernate Tools 3.6.0



/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer codigo;
     private OpcionDePerfil opcionDePerfil;
     private Boolean insertar;
     private Boolean consultar;
     private Boolean modificar;
     private Boolean eliminar;

    public Rol() {
    }

	
    public Rol(OpcionDePerfil opcionDePerfil) {
        this.opcionDePerfil = opcionDePerfil;
    }
    public Rol(OpcionDePerfil opcionDePerfil, Boolean insertar, Boolean consultar, Boolean modificar, Boolean eliminar) {
       this.opcionDePerfil = opcionDePerfil;
       this.insertar = insertar;
       this.consultar = consultar;
       this.modificar = modificar;
       this.eliminar = eliminar;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public OpcionDePerfil getOpcionDePerfil() {
        return this.opcionDePerfil;
    }
    
    public void setOpcionDePerfil(OpcionDePerfil opcionDePerfil) {
        this.opcionDePerfil = opcionDePerfil;
    }
    public Boolean getInsertar() {
        return this.insertar;
    }
    
    public void setInsertar(Boolean insertar) {
        this.insertar = insertar;
    }
    public Boolean getConsultar() {
        return this.consultar;
    }
    
    public void setConsultar(Boolean consultar) {
        this.consultar = consultar;
    }
    public Boolean getModificar() {
        return this.modificar;
    }
    
    public void setModificar(Boolean modificar) {
        this.modificar = modificar;
    }
    public Boolean getEliminar() {
        return this.eliminar;
    }
    
    public void setEliminar(Boolean eliminar) {
        this.eliminar = eliminar;
    }




}


