package com.teamj.distribuidas.model.database;
// Generated Feb 15, 2016 11:39:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Sistema generated by hbm2java
 */
public class Sistema implements java.io.Serializable {

    private Integer codigo;
    private String nombre;
    private String descripcion;
    private Boolean estado;
    private Set opcions = new HashSet(0);

    public Sistema() {
    }

    public Sistema(String nombre, String descripcion, Boolean estado, Set opcions) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estado = estado;
        this.opcions = opcions;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Set getOpcions() {
        return this.opcions;
    }

    public void setOpcions(Set opcions) {
        this.opcions = opcions;
    }

    @Override
    public String toString() {
        return nombre;
    }

}
