package com.teamj.distribuidas.model.database;
// Generated Feb 15, 2016 11:39:15 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Integer codigo;
    private Persona persona;
    private String nombreUsuario;
    private String password;
    private Date fechaCreacion;
    private Date fechaUltimoCambioClave;
    private String firmaElectronica;
    private Set usuarioXPerfils = new HashSet(0);

    public Usuario() {
    }

    public Usuario(Persona persona, String nombreUsuario, String password, Date fechaCreacion) {
        this.persona = persona;
        this.nombreUsuario = nombreUsuario;
        this.password = password;
        this.fechaCreacion = fechaCreacion;
    }

    public Usuario(Persona persona, String nombreUsuario, String password, Date fechaCreacion, Date fechaUltimoCambioClave, String firmaElectronica, Set usuarioXPerfils) {
        this.persona = persona;
        this.nombreUsuario = nombreUsuario;
        this.password = password;
        this.fechaCreacion = fechaCreacion;
        this.fechaUltimoCambioClave = fechaUltimoCambioClave;
        this.firmaElectronica = firmaElectronica;
        this.usuarioXPerfils = usuarioXPerfils;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public String getNombreUsuario() {
        return this.nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaUltimoCambioClave() {
        return this.fechaUltimoCambioClave;
    }

    public void setFechaUltimoCambioClave(Date fechaUltimoCambioClave) {
        this.fechaUltimoCambioClave = fechaUltimoCambioClave;
    }

    public String getFirmaElectronica() {
        return this.firmaElectronica;
    }

    public void setFirmaElectronica(String firmaElectronica) {
        this.firmaElectronica = firmaElectronica;
    }

    public Set getUsuarioXPerfils() {
        return this.usuarioXPerfils;
    }

    public void setUsuarioXPerfils(Set usuarioXPerfils) {
        this.usuarioXPerfils = usuarioXPerfils;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + Objects.hashCode(this.codigo);
        hash = 89 * hash + Objects.hashCode(this.persona);
        hash = 89 * hash + Objects.hashCode(this.nombreUsuario);
        hash = 89 * hash + Objects.hashCode(this.password);
        hash = 89 * hash + Objects.hashCode(this.fechaCreacion);
        hash = 89 * hash + Objects.hashCode(this.fechaUltimoCambioClave);
        hash = 89 * hash + Objects.hashCode(this.firmaElectronica);
        hash = 89 * hash + Objects.hashCode(this.usuarioXPerfils);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Usuario other = (Usuario) obj;
        if (!Objects.equals(this.codigo, other.codigo)) {
            return false;
        }
        if (!Objects.equals(this.persona, other.persona)) {
            return false;
        }
        if (!Objects.equals(this.nombreUsuario, other.nombreUsuario)) {
            return false;
        }
        if (!Objects.equals(this.password, other.password)) {
            return false;
        }
        if (!Objects.equals(this.fechaCreacion, other.fechaCreacion)) {
            return false;
        }
        if (!Objects.equals(this.fechaUltimoCambioClave, other.fechaUltimoCambioClave)) {
            return false;
        }
        if (!Objects.equals(this.firmaElectronica, other.firmaElectronica)) {
            return false;
        }
        if (!Objects.equals(this.usuarioXPerfils, other.usuarioXPerfils)) {
            return false;
        }
        return true;
    }

}
